logo: /images/image.jpg
title: Michael David
description: An aspiring Data Analyst looking to showcase my skills and be of an asset to your company.
# show dowloads: True
theme: jekyll-theme-minimal 
